import type { DiagnosisResult } from '$lib/types';

// 1. INTREFACE (Abstraction)
// Defines the contract that all report types must follow.
export interface IReport {
    generate(data: DiagnosisResult, patientName: string): string;
    getType(): string;
}

// 2. CONCRETE CLASSES (Polymorphism)
// Implementation for JSON format
export class JSONReport implements IReport {
    generate(data: DiagnosisResult, patientName: string): string {
        const report = {
            id: crypto.randomUUID(),
            timestamp: new Date().toISOString(),
            patient: patientName,
            diagnosis: data
        };
        return JSON.stringify(report, null, 2);
    }

    getType(): string {
        return "application/json";
    }
}

// Implementation for Plain Text format
export class TextReport implements IReport {
    generate(data: DiagnosisResult, patientName: string): string {
        const d = data.disease;
        return `
========================================
LAPORAN MEDIS - SiDia AI
========================================
Tanggal : ${new Date().toLocaleString()}
Pasien  : ${patientName}
----------------------------------------
DIAGNOSIS : ${d?.name.toUpperCase()}
Confidence: ${Math.round((data.matchCount / data.totalSymptoms) * 100)}%

[Deskripsi]
${d?.description}

[Saran Medis]
${d?.advice}

[Gejala Cocok]
${d?.matchedSymptoms?.join(', ')}
========================================
        `.trim();
    }

    getType(): string {
        return "text/plain";
    }
}

// Implementation for HTML format (Print-ready)
export class HTMLReport implements IReport {
    generate(data: DiagnosisResult, patientName: string): string {
        const d = data.disease;
        const confidence = Math.round((data.matchCount / data.totalSymptoms) * 100);

        return `
            <div style="font-family: sans-serif; padding: 2rem; border: 2px solid #000; max-width: 800px; margin: 0 auto;">
                <h1 style="color: #ff2d55; letter-spacing: 4px; text-transform: uppercase; border-bottom: 2px solid #000; padding-bottom: 1rem;">
                    SiDia-AI Medical Record
                </h1>
                <div style="margin: 2rem 0; display: grid; grid-template-columns: 1fr 1fr; gap: 2rem;">
                    <div>
                        <strong>Patient Identifier:</strong><br>
                        ${patientName}
                    </div>
                    <div style="text-align: right;">
                        <strong>Timestamp:</strong><br>
                        ${new Date().toLocaleString()}
                    </div>
                </div>
                
                <div style="background: #f0f0f0; padding: 2rem; border-radius: 8px;">
                    <h2 style="margin-top: 0; font-size: 2.5rem; color: #135bec;">${d?.name}</h2>
                    <div style="display: inline-block; background: #000; color: #fff; padding: 0.5rem 1rem; border-radius: 4px; font-weight: bold;">
                        CONFIDENCE: ${confidence}%
                    </div>
                    <p style="font-size: 1.2rem; line-height: 1.6;">${d?.description}</p>
                </div>

                <div style="margin-top: 2rem; border: 1px dashed #999; padding: 1rem;">
                    <h3 style="color: #666; text-transform: uppercase;">Medical Protocol</h3>
                    <p>${d?.advice}</p>
                </div>
                
                <footer style="margin-top: 4rem; text-align: center; color: #999; font-size: 0.8rem;">
                    Generated by Gemini Neural Engine v2.5 // SiDia-AI System
                </footer>
            </div>
        `.trim();
    }

    getType(): string {
        return "text/html";
    }
}

// 3. FACTORY CLASS (Creator)
// Encapsulates the logic of object creation. 
// The client doesn't need to know 'new TextReport()', just 'Factory.create("text")'.
export class ReportFactory {
    static createReport(type: 'json' | 'text' | 'html'): IReport {
        switch (type) {
            case 'json':
                return new JSONReport();
            case 'text':
                return new TextReport();
            case 'html':
                return new HTMLReport();
            default:
                throw new Error("Tipe laporan tidak dikenal");
        }
    }
}
